embedding_model: "all-MiniLM-L6-v2" # default: "all-MiniLM-L6-v2"
ranker: "ms-marco-TinyBERT-L-2-v2"
task: "text-matching"
faiss_M: 64 # default: 32
faiss_efConstruction: 256 # default: 40
faiss_efSearch: 64 # default: 16
# matryoshka_dim: 256